on:
  push:
    branches:
      - master
  pull_request:

name: Continuous integration

jobs:
  check:
    name: Linux-Check
    runs-on: ubuntu-latest
    steps:
      - name: Install liboping
        run: sudo apt-get install -y liboping-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: cargo +nightly check

  mac-check:
    name: MacOS-Check
    runs-on: macos-latest
    steps:
      - name: Install liboping
        run: sudo brew install liboping
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: cargo +nightly check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Install liboping
        run: sudo apt-get install -y liboping-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: cargo +nightly test

  mac-test:
    name: MacOS-Test
    runs-on: macos-latest
    steps:
      - name: Install liboping
        run: sudo brew install liboping
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: cargo +nightly test
